discourse-3.1.2/config/routes.rb
    get "/favicon.ico", to: proc { [200, {}, [""]] } if Rails.env.test?

    post "webhooks/aws" => "webhooks#aws"
    post "webhooks/mailgun" => "webhooks#mailgun"
    post "webhooks/mailjet" => "webhooks#mailjet"
    post "webhooks/mailpace" => "webhooks#mailpace"
    post "webhooks/mandrill" => "webhooks#mandrill"
    get "webhooks/mandrill" => "webhooks#mandrill_head"
    post "webhooks/postmark" => "webhooks#postmark"
    post "webhooks/sendgrid" => "webhooks#sendgrid"
    post "webhooks/sparkpost" => "webhooks#sparkpost"

    scope path: nil, format: true, constraints: { format: :xml } do
      resources :sitemap, only: [:index]
      get "/sitemap_:page" => "sitemap#page", :page => /[1-9][0-9]*/
      get "/sitemap_recent" => "sitemap#recent"
      get "/news" => "sitemap#news"
    end

    scope path: nil, constraints: { format: /.*/ } do
      if Rails.env.development?
        mount Sidekiq::Web => "/sidekiq"
        mount Logster::Web => "/logs"
      else
        # only allow sidekiq in master site
        mount Sidekiq::Web => "/sidekiq", :constraints => AdminConstraint.new(require_master: true)
        mount Logster::Web => "/logs", :constraints => AdminConstraint.new
      end
    end

    resources :about, only: [:index] do
      collection { get "live_post_counts" }
    end

    get "finish-installation" => "finish_installation#index"
    get "finish-installation/register" => "finish_installation#register"
    post "finish-installation/register" => "finish_installation#register"
    get "finish-installation/confirm-email" => "finish_installation#confirm_email"
    put "finish-installation/resend-email" => "finish_installation#resend_email"

    get "pub/check-slug" => "published_pages#check_slug"
    get "pub/by-topic/:topic_id" => "published_pages#details"
    put "pub/by-topic/:topic_id" => "published_pages#upsert"
    delete "pub/by-topic/:topic_id" => "published_pages#destroy"
    get "pub/:slug" => "published_pages#show"

    resources :directory_items, only: [:index]

    get "site" => "site#site"
    namespace :site do
      get "settings"
      get "custom_html"
      get "banner"
      get "emoji"
    end

    get "site/basic-info" => "site#basic_info"
    get "site/statistics" => "site#statistics"

    get "srv/status" => "forums#status"

    get "wizard" => "wizard#index"
    get "wizard/steps/:id" => "wizard#index"
    put "wizard/steps/:id" => "steps#update"

    namespace :admin, constraints: StaffConstraint.new do
      get "" => "admin#index"

      get "plugins" => "plugins#index"

      resources :site_settings, only: %i[index update], constraints: AdminConstraint.new do
        collection { get "category/:id" => "site_settings#index" }

        put "user_count" => "site_settings#user_count"
      end

      get "reports" => "reports#index"
      get "reports/bulk" => "reports#bulk"
      get "reports/:type" => "reports#show"

      resources :groups, only: [:create] do
        member do
          delete "owners" => "groups#remove_owner"
          put "primary" => "groups#set_primary"
        end
      end
      resources :groups, only: [:destroy], constraints: AdminConstraint.new do
        collection { put "automatic_membership_count" => "groups#automatic_membership_count" }
      end

      resources :users, id: RouteFormat.username, only: %i[index destroy] do
        collection do
          get "list" => "users#index"
          get "list/:query" => "users#index"
          get "ip-info" => "users#ip_info"
          delete "delete-others-with-same-ip" => "users#delete_other_accounts_with_same_ip"
          get "total-others-with-same-ip" => "users#total_other_accounts_with_same_ip"
          put "approve-bulk" => "users#approve_bulk"
        end
        delete "penalty_history", constraints: AdminConstraint.new
        put "suspend"
        put "delete_posts_batch"
        put "unsuspend"
        put "revoke_admin", constraints: AdminConstraint.new
        put "grant_admin", constraints: AdminConstraint.new
        put "revoke_moderation", constraints: AdminConstraint.new
        put "grant_moderation", constraints: AdminConstraint.new
        put "approve"
        post "log_out", constraints: AdminConstraint.new
        put "activate"
        put "deactivate"
        put "silence"
        put "unsilence"
        put "trust_level"
        put "trust_level_lock"
        put "primary_group"
        post "groups" => "users#add_group", :constraints => AdminConstraint.new
        delete "groups/:group_id" => "users#remove_group", :constraints => AdminConstraint.new
        get "badges"
        get "leader_requirements" => "users#tl3_requirements"
        get "tl3_requirements"
        put "anonymize"
        post "merge"
        post "reset-bounce-score"
        put "disable_second_factor"
        delete "sso_record"
      end
      get "users/:id.json" => "users#show", :defaults => { format: "json" }
      get "users/:id/:username" => "users#show",
          :constraints => {
            username: RouteFormat.username,
          },
          :as => :user_show
      get "users/:id/:username/badges" => "users#show"
      get "users/:id/:username/tl3_requirements" => "users#show"

      post "users/sync_sso" => "users#sync_sso", :constraints => AdminConstraint.new

      resources :impersonate, only: %i[index create], constraints: AdminConstraint.new

      resources :email, only: [:index], constraints: AdminConstraint.new do
        collection do
          post "test"
          get "sent"
          get "skipped"
          get "bounced"
          get "received"
          get "rejected"
          get "/incoming/:id" => "email#incoming"
          get "/incoming_from_bounced/:id" => "email#incoming_from_bounced"
          get "preview-digest" => "email#preview_digest"
          post "send-digest" => "email#send_digest"
          get "smtp_should_reject"
          post "handle_mail"
          get "advanced-test"
          post "advanced-test" => "email#advanced_test"
        end
      end

      scope "/logs" do
        resources :staff_action_logs, only: [:index]
        get "staff_action_logs/:id/diff" => "staff_action_logs#diff"
        resources :screened_emails, only: %i[index destroy]
        resources :screened_ip_addresses, only: %i[index create update destroy]
        resources :screened_urls, only: [:index]
        resources :search_logs, only: [:index]
        get "search_logs/term/" => "search_logs#term"
      end

      get "/logs" => "staff_action_logs#index"

      # alias
      get "/logs/watched_words", to: redirect(relative_url_root + "admin/customize/watched_words")
      get "/logs/watched_words/*path",
          to: redirect(relative_url_root + "admin/customize/watched_words/%{path}")

      get "customize" => "color_schemes#index", :constraints => AdminConstraint.new
      get "customize/themes" => "themes#index", :constraints => AdminConstraint.new
      get "customize/colors" => "color_schemes#index", :constraints => AdminConstraint.new
      get "customize/colors/:id" => "color_schemes#index", :constraints => AdminConstraint.new
      get "customize/permalinks" => "permalinks#index", :constraints => AdminConstraint.new
      get "customize/embedding" => "embedding#show", :constraints => AdminConstraint.new
      put "customize/embedding" => "embedding#update", :constraints => AdminConstraint.new

      resources :themes,
                only: %i[index create show update destroy],
                constraints: AdminConstraint.new do
        member do
          get "preview" => "themes#preview"
          put "setting" => "themes#update_single_setting"
        end
        collection do
          post "import" => "themes#import"
          post "upload_asset" => "themes#upload_asset"
          post "generate_key_pair" => "themes#generate_key_pair"
        end
      end

      scope "/customize", constraints: AdminConstraint.new do
        resources :user_fields,
                  only: %i[index create update destroy],
                  constraints: AdminConstraint.new
        resources :emojis, only: %i[index create destroy], constraints: AdminConstraint.new
        resources :form_templates, constraints: AdminConstraint.new, path: "/form-templates" do
          collection { get "preview" => "form_templates#preview" }
        end

        get "themes/:id/:target/:field_name/edit" => "themes#index"
        get "themes/:id" => "themes#index"
        get "themes/:id/export" => "themes#export"

        # They have periods in their URLs often:
        get "site_texts" => "site_texts#index"
        get "site_texts/:id.json" => "site_texts#show", :constraints => { id: /[\w.\-\+\%\&]+/i }
        get "site_texts/:id" => "site_texts#show", :constraints => { id: /[\w.\-\+\%\&]+/i }
        put "site_texts/:id.json" => "site_texts#update", :constraints => { id: /[\w.\-\+\%\&]+/i }
        put "site_texts/:id" => "site_texts#update", :constraints => { id: /[\w.\-\+\%\&]+/i }
        delete "site_texts/:id.json" => "site_texts#revert",
               :constraints => {
                 id: /[\w.\-\+\%\&]+/i,
               }
        delete "site_texts/:id" => "site_texts#revert", :constraints => { id: /[\w.\-\+\%\&]+/i }
        put "site_texts/:id/dismiss_outdated" => "site_texts#dismiss_outdated",
            :constraints => {
              id: /[\w.\-\+\%\&]+/i,
            }
        put "site_texts/:id/dismiss_outdated.json" => "site_texts#dismiss_outdated",
            :constraints => {
              id: /[\w.\-\+\%\&]+/i,
            }

        get "reseed" => "site_texts#get_reseed_options"
        post "reseed" => "site_texts#reseed"

        get "email_templates" => "email_templates#index"
        get "email_templates/(:id)" => "email_templates#show", :constraints => { id: /[0-9a-z_.]+/ }
        put "email_templates/(:id)" => "email_templates#update",
            :constraints => {
              id: /[0-9a-z_.]+/,
            }

discourse-3.1.2/app/helpers/list_helper.rb
# frozen_string_literal: true

module ListHelper
  def page_links(topic)
    posts = topic.posts_count
    max_pages = 10
    total_pages = (posts / TopicView.chunk_size) + (posts == TopicView.chunk_size ? 0 : 1)

    return if total_pages < 2

    page = [total_pages - (max_pages + 1), 2].max

    result = "("
    while page <= total_pages
      result << " <a href='#{topic.relative_url}?page=#{page}'>#{page}</a> "
      page += 1
    end

    result << ")"
    result.html_safe
  end
end

discourse-3.1.2/app/views/list/list.erb
<%- if include_crawler_content? %>

<%= server_plugin_outlet "topic_list_header" %>

<%- if SiteSetting.tagging_enabled && @tag_id %>
  <h1>
    <%= link_to "#{Discourse.base_url}/tag/#{@tag_id}", itemprop: 'item' do %>
      <span itemprop='name'><%= @tag_id %></span>
    <% end %>
  </h1>
<% end %>

<% if @category %>
  <h1>
    <% if @category.parent_category %>
      <%= link_to @category.parent_category.url, itemprop: 'item' do %>
        <span itemprop='name'><%= @category.parent_category.name %></span>
      <% end %>
      &nbsp;
    <% end %>

    <%= link_to @category.url, itemprop: 'item' do %>
      <span itemprop='name'><%= @category.name %></span>
    <% end %>
  </h1>
  <br/>

  <% if params[:page].to_i == 0 && @subcategories.present? %>
    <% @subcategories.each do |subcategory| %>
      <a href='<%= subcategory.url %>'>
        <span itemprop='name'><%= subcategory.name %></span>
      </a>
      <% if subcategory.description.present? %>
        <span itemprop='description'><%= subcategory.description_text %></span>
      <% end %>
    <% end %>
    <br/>
  <% end %>
<% end %>

<div class="topic-list-container" itemscope itemtype='http://schema.org/ItemList'>
  <meta itemprop='itemListOrder' content='http://schema.org/ItemListOrderDescending'>

  <table class='topic-list'>

    <thead>
      <tr>
        <th><%= t 'js.topic.title' %></th>
        <th></th>
        <th class="replies"><%= t 'js.replies' %></th>
        <th class="views"><%= t 'js.views' %></th>
        <th><%= t 'js.activity' %></th>
      </tr>
    </thead>

    <tbody>
      <% @list.topics.each_with_index do |t,i| %>
        <tr class="topic-list-item">
          <td class="main-link" itemprop='itemListElement' itemscope itemtype='http://schema.org/ListItem'>
            <meta itemprop='position' content='<%= i + 1 %>'>
            <span class="link-top-line">
              <a itemprop='url' href='<%= t.url %>' class='title raw-link raw-topic-link'><%= t.title %></a>
            </span>
            <div class="link-bottom-line">
              <% if (!@category || @category.has_children?) && t.category && !t.category.uncategorized? %>
                <a href='<%= t.category.url %>' class='badge-wrapper bullet'>
                  <span class='badge-category-bg' style='background-color: #<%= t.category.color %>'></span>
                  <span class='badge-category clear-badge'>
                    <span class='category-name'><%= t.category.name %></span>
                  </span>
                </a>
              <% end %>
              <% if tags = t.visible_tags(guardian) %>
                <div class="discourse-tags">
                  <% tags.each_with_index do |tag, index| %>
                    <a href='<%= tag.full_url %>' class='discourse-tag'><%= tag.name %></a>
                    <% if index < tags.size - 1 %>,&nbsp;<% end %>
                  <% end %>
                </div>
              <% end %>
            </div>
            <% if t.pinned_until && (t.pinned_until > Time.zone.now) && (t.pinned_globally || @list.category) && t.excerpt %>
              <p class='excerpt'>
                <%= t.excerpt.html_safe %>
              </p>
            <% end %>
          </td>
          <td class='posters'>
            <% t.posters.each do |poster| %>
              <a href="<%= Discourse.base_url %>/u/<%= poster.user.username %>" class="<%= poster.extras %>">
                <img width="25" height="25" src="<%= poster.user.avatar_template.gsub('{size}', '25') %>" class="avatar" title='<%= h(poster.name_and_description) %>' aria-label='<%= h(poster.name_and_description) %>'>
              </a>
            <% end %>
          </td>
          <td class="replies">
            <span class='posts' title='<%= t 'posts' %>'><%= t.posts_count - 1 %></span>
          </td>
          <td class="views">
            <span class='views' title='<%= t 'views' %>'><%= t.views %></span>
          </td>
          <td>
            <%= I18n.l(t.last_posted_at || t.created_at, format: :date_only) %>
          </td>
        </tr>
      <% end %>
    </tbody>

  </table>
</div>

<% if @list.topics.length > 0 && @list.more_topics_url %>
  <div class="navigation" role='navigation' itemscope itemtype='http://schema.org/SiteNavigationElement'>
    <% if params[:page].to_i > 0 %>
      <span itemprop='name'><a href='<%= @list.prev_topics_url %>' rel='prev' itemprop='url'><%= t 'prev_page' %></a> &nbsp;</span>
    <% end %>
    <% if @list.topics.size == @list.per_page %>
      <span itemprop='name'><b><a href='<%= @list.more_topics_url %>' rel='next' itemprop='url'><%= t 'next_page' %></a></b></span>
    <% end %>
  </div>

  <% content_for :head do %>
    <% if params[:page].to_i > 0 %>
      <link rel="prev" href="<%= @list.prev_topics_url -%>">
    <% end %>
    <link rel="next" href="<%= @list.more_topics_url -%>">
  <% end %>
<% end %>

<%- end %> <!-- include_crawler_content? -->

<% if @rss %>
  <% content_for :head do %>
    <%= auto_discovery_link_tag(:rss, "#{Discourse.base_url}/posts.rss", title: I18n.t("rss_description.posts")) %>
    <%= auto_discovery_link_tag(:rss, { action: "#{@rss}_feed", params: @params || {} }, title: I18n.t("rss_description.#{@rss_description}")) %>
  <% end %>
<% end %>

<% if @category %>
  <% content_for :head do %>
    <%= auto_discovery_link_tag(:rss, { action: :category_feed }, rel: 'alternate nofollow', title: t('rss_topics_in_category', category: @category.name)) %>
    <%= raw crawlable_meta_data(title: @category.name, description: @category.description, image: @category.uploaded_logo&.url.presence) %>
  <% end %>
<% elsif @tag_id %>
  <% content_for :head do %>
    <%= raw crawlable_meta_data(title: @title, description: @description_meta) %>
  <% end %>
<% else %>
  <% content_for :head do %>
    <%= raw crawlable_meta_data(title: SiteSetting.title, description: SiteSetting.site_description) %>
  <% end %>
<% end %>

<% if @title %>
  <% content_for :title do %><%= @title %><% end %>
<% elsif @category %>
  <% content_for :title do %><%= @category.name %> - <%= SiteSetting.title %><% end %>
<% elsif params[:page].to_i > 1 %>
  <% content_for :title do %><%=t 'page_num', num: params[:page].to_i + 1 %> - <%= SiteSetting.title %><% end %>
<% end %>

discourse-3.1.2/app/views/list/list.rss.erb
<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:discourse="http://www.discourse.org/" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <% lang = SiteSetting.find_by_name('default_locale').try(:value) %>
    <% site_email = SiteSetting.find_by_name('contact_email').try(:value) %>
    <title><%= @title %></title>
    <link><%= @link %></link>
    <description><%= @description %></description>
    <% if lang %><language><%= lang.sub('_', '-')%></language><% end %>
    <% if @topic_list.topics && @topic_list.topics.length > 0 %>
      <lastBuildDate><%= @topic_list.topics.first.created_at.rfc2822 %></lastBuildDate>
      <atom:link href="<%= @atom_link %>" rel="self" type="application/rss+xml" />
      <% @topic_list.topics.each do |topic| %>
        <% topic_url = topic.url -%>
        <item>
          <title><%= topic.title %></title>
          <dc:creator><![CDATA[<%= rss_creator(topic.user) -%>]]></dc:creator>
          <category><%= topic.category.name %></category>
          <description><![CDATA[
            <%- if first_post = topic.ordered_posts.first %>
            <%= PrettyText.format_for_email(first_post.cooked, first_post).html_safe %>
            <%- end %>
            <p><small><%= t 'rss_num_posts', count: topic.posts_count %> - <%= t 'rss_num_participants', count: topic.participant_count %></small></p>
            <p><%= link_to t('read_full_topic'), topic_url %></p>
          ]]></description>
          <link><%= topic_url %></link>
          <pubDate><%= topic.created_at.rfc2822 %></pubDate>
          <discourse:topicPinned><%= topic.pinned_at ? 'Yes' : 'No' %></discourse:topicPinned>
          <discourse:topicClosed><%= topic.closed ? 'Yes' : 'No' %></discourse:topicClosed>
          <discourse:topicArchived><%= topic.archived ? 'Yes' : 'No' %></discourse:topicArchived>
          <guid isPermaLink="false"><%= Discourse.current_hostname %>-topic-<%= topic.id %></guid>
          <source url="<%= topic_url %>.rss"><%= topic.title %></source>
        </item>
      <% end %>
    <% end %>
  </channel>
</rss>